<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

## *Data Science Unit 4 Sprint 2*

# Sprint Challenge - Neural Network Foundations

Table of Problems

1. [Defining Neural Networks](#Q1)
2. [Chocolate Gummy Bears](#Q2)
    - Perceptron
    - Multilayer Perceptron
4. [Keras MMP](#Q3)

<a id="Q1"></a>
## 1. Define the following terms:

- **Neuron:**
- **Input Layer:**
- **Hidden Layer:**
- **Output Layer:**
- **Activation:**
- **Backpropagation:**


## 2. Chocolate Gummy Bears <a id="Q2"></a>

Right now, you're probably thinking, "yuck, who the hell would eat that?". Great question. Your candy company wants to know too. And you thought I was kidding about the [Chocolate Gummy Bears](https://nuts.com/chocolatessweets/gummies/gummy-bears/milk-gummy-bears.html?utm_source=google&utm_medium=cpc&adpos=1o1&gclid=Cj0KCQjwrfvsBRD7ARIsAKuDvMOZrysDku3jGuWaDqf9TrV3x5JLXt1eqnVhN0KM6fMcbA1nod3h8AwaAvWwEALw_wcB). 

Let's assume that a candy company has gone out and collected information on the types of Halloween candy kids ate. Our candy company wants to predict the eating behavior of witches, warlocks, and ghosts -- aka costumed kids. They shared a sample dataset with us. Each row represents a piece of candy that a costumed child was presented with during "trick" or "treat". We know if the candy was `chocolate` (or not chocolate) or `gummy` (or not gummy). Your goal is to predict if the costumed kid `ate` the piece of candy. 

If both chocolate and gummy equal one, you've got a chocolate gummy bear on your hands!?!?!
![Chocolate Gummy Bear](https://ed910ae2d60f0d25bcb8-80550f96b5feb12604f4f720bfefb46d.ssl.cf1.rackcdn.com/3fb630c04435b7b5-2leZuM7_-zoom.jpg)

In [1]:
import pandas as pd
candy = pd.read_csv('chocolate_gummy_bears.csv')

In [2]:
candy.head()

chocolate  gummy  ate
0          0      1    1
1          1      0    1
2          0      1    1
3          0      0    0
4          1      1    0

### Perceptron

To make predictions on the `candy` dataframe. Build and train a Perceptron using numpy. Your target column is `ate` and your features: `chocolate` and `gummy`. Do not do any feature engineering. :P

Once you've trained your model, report your accuracy. You will not be able to achieve more than ~50% with the simple perceptron. Explain why you could not achieve a higher accuracy with the *simple perceptron* architecture, because it's possible to achieve ~95% accuracy on this dataset. Provide your answer in markdown (and *optional* data anlysis code) after your perceptron implementation. 

In [67]:
# Start your candy perceptron here
import numpy as np

X = candy[['chocolate', 'gummy']].values
y = candy[['ate']].values


def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1 - sx)

weights = 2 * np.random.random((2, 1)) - 1

weighted_sum = np.dot(X, weights)
activated_output = sigmoid(weighted_sum)
print(error)
print(np.mean(error))

[[0.19661193]
 [0.19661193]
 [0.19661193]
 ...
 [0.19661193]
 [0.19661193]
 [0.19661193]]
0.2062789831836382


Simple or Single layer Perceptrons only have an input layer and an output layer. There are no hidden layers to provide further computation

### Multilayer Perceptron <a id="Q3"></a>

Using the sample candy dataset, implement a Neural Network Multilayer Perceptron class that uses backpropagation to update the network's weights. Your Multilayer Perceptron should be implemented in Numpy. 
Your network must have one hidden layer.

Once you've trained your model, report your accuracy. Explain why your MLP's performance is considerably better than your simple perceptron's on the candy dataset. 

In [63]:
class Neural_Network:
    def __init__(self, input_nodes = 2, hidden_nodes = 3, output_nodes = 1):
        self.input_nodes = input_nodes
        self.hidden_nodes = hidden_nodes
        self.output_nodes = output_nodes
    
    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def __sigmoid_derivative(self, x):
        return x * (1 - x)
    
    def __feed_forward(self, X):
        self.weights1 = np.random.rand(self.input_nodes, self.hidden_nodes)
        self.weights2 = np.random.rand(self.hidden_nodes, self.output_nodes)
        
        self.hidden_sum = np.dot(X, self.weights1)
        self.activated_hidden = self.__sigmoid(self.hidden_sum)
        
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        self.activated_output = self.__sigmoid(self.output_sum)
        
        return self.activated_output
    
    def __backward(self, X, y, o):
        self.o_error = y - o
        
        self.o_delta = self.o_error * self.__sigmoid_derivative(o)
        self.z2_error = self.o_delta.dot(self.weights2.T)
        
        self.z2_delta = self.z2_error - self.__sigmoid_derivative(self.activated_hidden)
        
        self.weights1 = X.T.dot(self.z2_delta)
        self.weights2 = self.activated_hidden.T.dot(self.o_delta)
    
    def train(self, X, y, n_iter = 10):
        self.o = self.__feed_forward(X)
        self.__backward(X, y, self.o)

In [70]:
nn = Neural_Network(input_nodes=X.shape[1], hidden_nodes=8)
nn.train(X, y)

In [72]:
print(nn.o_error)

[[0.02002139]
 [0.021823  ]
 [0.02002139]
 ...
 [0.02002139]
 [0.02002139]
 [0.021823  ]]
[[0.97997861]
 [0.978177  ]
 [0.97997861]
 ...
 [0.97997861]
 [0.97997861]
 [0.978177  ]]


With a Multi-layer Perceptron hidden layers are used to handle further processing of the data from the input. By hidden layers the data is iteerated more times in order to calculate a more accurate output. Before it was running through a single iteration with a single set of weights to return an output that wasn't very accurate. Adding hidden layers allows the data to go through multiple iterations with more sets of weights, which end up producing a more accurate output.

P.S. Don't try candy gummy bears. They're disgusting. 

## 3. Keras MMP <a id="Q3"></a>

Implement a Multilayer Perceptron architecture of your choosing using the Keras library. Train your model and report its baseline accuracy. Then hyperparameter tune at least two parameters and report your model's accuracy.
Use the Heart Disease Dataset (binary classification)
Use an appropriate loss function for a binary classification task
Use an appropriate activation function on the final layer of your network.
Train your model using verbose output for ease of grading.
Use GridSearchCV or RandomSearchCV to hyperparameter tune your model. (for at least two hyperparameters)
When hyperparameter tuning, show you work by adding code cells for each new experiment.
Report the accuracy for each combination of hyperparameters as you test them so that we can easily see which resulted in the highest accuracy.
You must hyperparameter tune at least 3 parameters in order to get a 3 on this section.

In [77]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

df = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/heart.csv')
df = df.sample(frac=1)
print(df.shape)
df.head()

(303, 14)


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
213   61    0   0       145   307    0        0      146      1      1.0   
261   52    1   0       112   230    0        1      160      0      0.0   
228   59    1   3       170   288    0        0      159      0      0.2   
68    44    1   1       120   220    0        1      170      0      0.0   
290   61    1   0       148   203    0        1      161      0      0.0   

     slope  ca  thal  target  
213      1   0     3       0  
261      2   1     2       0  
228      1   0     3       0  
68       2   0     2       1  
290      2   1     3       0

In [76]:
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [81]:
model = Sequential()
X = df[['age', 'cp', 'trestbps', 'chol']]
y = df[['target']]
x_train, y_train, x_test, y_test = train_test_split(X, y)

scalar = StandardScaler()
scalar.fit(x_train, y_train)

model.add(Dense(4, input_dim=4, activation='sigmoid'))
model.add(Dense(1, activation='softmax'))

/Users/ashwin/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:645: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
